title: Vincent Carey Biostatistics/Genome Bioinformatics
logo: /assets/img/vjclogo1.png
description: Vince Carey's team does <a href=http://www.bioconductor.org>Bioconductor</a>, NCI ITCR, <a href="http://anvilproject.org">NHGRI AnVIL</a>, and various <a href="https://clinicaltrials.gov/ct2/show/NCT02817074">NIH clinical</a> <a href="https://clinicaltrials.gov/ct2/show/NCT00920621">trials</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
